-- 코드를 입력하세요
SELECT BOOK.CATEGORY, COALESCE(SUM(SALES),0) AS TOTAL_SALES
FROM BOOK 
LEFT JOIN BOOK_SALES AS SALES ON BOOK.BOOK_ID = SALES.BOOK_ID
WHERE EXTRACT(YEAR FROM SALES_DATE) = 2022 AND EXTRACT(MONTH FROM SALES_DATE) = 1
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY ;